import os
import sys
import requests

BASE_URL = "http://127.0.0.1:5000"

def run_batch_processor(dataset_folder=None):
    if not dataset_folder:
        if len(sys.argv) > 1:
            dataset_folder = sys.argv[1]
        else:
            default_dir = os.path.join(os.path.dirname(__file__), "static", "uploads")
            print(f"No folder specified. Usage: python batch.py <path_to_images_folder>")
            print(f"Defaulting to local uploads folder: {default_dir}\n")
            dataset_folder = default_dir

    if not os.path.exists(dataset_folder):
        print(f"[ERROR] Dataset folder path '{dataset_folder}' does not exist!")
        return

    print(f"Starting batch process for folder: {dataset_folder}")
    print("Logging into Sentri OS...")
    
    try:
        login_response = requests.post(f"{BASE_URL}/api/auth/login", json={
            "username": "admin",
            "password": "adminpassword"
        })
    except Exception as e:
        print("[ERROR] Login failed. Is your Flask server running on http://127.0.0.1:5000?")
        return

    if login_response.status_code != 200:
        print("[ERROR] Login failed. Invalid admin credentials!")
        return

    token = login_response.json().get("token")
    headers = {"Authorization": f"Bearer {token}"}
    print("[SUCCESS] Logged in successfully! Processing batch images...\n")

    success_count = 0
    fail_count = 0

    for root, dirs, files in os.walk(dataset_folder):
        for filename in files:
            # Skip output annotated images generated by detector
            if filename.startswith("det_") or filename.startswith("annotated_"):
                continue

            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.webp')):
                file_path = os.path.join(root, filename)
                
                with open(file_path, 'rb') as img_file:
                    files_payload = {'file': (filename, img_file, 'image/jpeg')}
                    try:
                        res = requests.post(f"{BASE_URL}/api/detect/image", headers=headers, files=files_payload)
                        if res.status_code == 200:
                            data = res.json()
                            plate = data.get('plate_number', 'N/A')
                            v_type = data.get('violation_type', 'N/A')
                            print(f"[ANALYZE] {filename} -> Plate: {plate} | Violation: {v_type}")
                            success_count += 1
                        else:
                            print(f"[WARNING] {filename} -> Failed to process (Error {res.status_code})")
                            fail_count += 1
                    except Exception as e:
                        print(f"[ERROR] Error connecting to server for {filename}: {e}")
                        fail_count += 1

    print(f"\n[COMPLETE] Batch processing finished! Successfully processed {success_count} images ({fail_count} failed).")

if __name__ == "__main__":
    run_batch_processor()